name: Build app and deploy to Tencent
on:
  push:
    branches:
      - main # main 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.SSH_KEY }}
          PUBLISH_REPOSITORY: W-HanYu/W-HanYu.github.io
          BRANCH: gh-pages

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: -rltgoDzvO --delete
            SOURCE: ./public/
            REMOTE_HOST: 82.157.235.67
            REMOTE_USER: root
            TARGET: /82.157.235.67
